version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: tactalyse-db
    restart: always
    ports:
      - 27017:27017

  api:
    depends_on:
      - mongodb
    build: ./api
    container_name: tactalyse-api
    ports:
      - 5000:5000
    restart: always
    links:
      - mongodb
    environment:
      - JWT_SECRET=JWTSECRETTOKEN
      - DB_URI=mongodb://mongodb:27017/users
      - PORT=5000
      - SALT_ROUNDS=10
      - MOLLIE_API_KEY=test_mKdenUnyR3FHCWMSndC4nSCEWVVyJD
      - STRIPE_API_KEY=sk_test_51MwhjWJMTSQqzUddwKUR2IDTSaF1ukB1hqz9AqgcqOGdHREmhekCArdd1KDVZuR6FDaCaAEQpw5ERX8HJmUJNxLg00Zqaehxmp

  frontend:
    build: ./frontend
    container_name: tactalyse-client
    ports:
      - 3000:3000
    restart: always
    environment:
      - NEXTAUTH_SECRET=JWTSECRETTOKEN #very secret
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000