name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build-test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install packages
        working-directory: ./api
        run: sudo npm install
      - name: build project
        working-directory: ./api
        run: sudo npm run build
      - name: run tests
        working-directory: ./api
        run: sudo npm run test

  build-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install packages
        working-directory: ./client
        run: sudo npm install

